title:               Jokerr.io
author:
  name: Josh Kerr
  #email: josh@jokerr.io
tagline:             'Home of the Jokerr'
description: >- # this means to ignore newlines until "baseurl:"
  Husband, Father, Developer/Architect
url: http://jokerr.io
baseurl: ''


#paginate: 5

# Permalinks
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

minima:
  social_links:
    twitter: jokerr
    github: jokerr
    flickr: jokerr
    instagram: jokerr917
    linkedin: joshuakerr
    keybase: jokerr

theme: minima

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  #- jekyll-gist